version: "3"
services:
  host:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/bash
  app:
    build: .
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgresql://${USER}@db:5432"
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/project
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${USER}
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  dbdata:
