version: "3"
services:
  app:
    build: .
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgresql://${USER}@db:5432"
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/project
    links:
      - db
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${USER}
    volumes:
      - dbdata
volumes:
  dbdata:
